import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import darkTheme from "./theme";
import Header from "@/components/Header";
import Provider from "@/components/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#18181c] text-white min-h-screen flex flex-col`}
      >
        <AppRouterCacheProvider>
          <Provider>
            <ThemeProvider theme={darkTheme}>
              <CssBaseline />
              <Header />
              <main className="flex-1 flex justify-center">
                <div className="w-full">{children}</div>
              </main>
              <footer className="w-full text-center py-4 text-sm text-gray-400 border-t border-gray-800">
                © {new Date().getFullYear()} Movie Web. All rights reserved.
              </footer>
            </ThemeProvider>
          </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
